import Head from 'next/head'
import axios from 'axios';
import styles from '../styles/Home.module.css'
import React, { useState, useEffect } from 'react';



export default function Home() {
  const [showdata, setShowdata] = useState([]);


const shwodetail = ()=>{

const dataa = {
  email: "me@me.com",
  username: "measdfasdf"
};

  const headers = {
  'Content-Type': 'application/json'  
}

axios.post("http://localhost:3000/api/hello", dataa, {
    headers: headers
  })
  .then((response) => {
    console.log(response.data)
    setShowdata(response.data.details)
  })
  .catch((error) => {
    console.log(error)
  })



}



console.log(showdata);




  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      




<button onClick={()=>shwodetail()}>Click</button>


      Welcome to Md. Rajon


    <div className="users">
        {showdata.map((user) => (
          <div className="user" key={user.id}>{user.name}</div>
        ))}
    </div>



    </>
  )
}
